# Generated by Django 3.1.7 on 2021-04-01 10:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLArgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/bill/github/mlopen/mlopen/mlopenapp/storage'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/bill/github/mlopen/mlopen/mlopenapp/storage'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MLPipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('ml_args', models.ManyToManyField(to='mlopenapp.MLArgs')),
                ('ml_models', models.ManyToManyField(to='mlopenapp.MLModel')),
            ],
        ),
    ]
