# Generated by Django 3.1.7 on 2021-04-01 14:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlopenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlargs',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/bill/github/mlopen/mlopen/mlopenapp/storage/args'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/bill/github/mlopen/mlopen/mlopenapp/storage/models'), upload_to=''),
        ),
    ]
